/**
 * Download utility functions for Sage AI outputs
 */

import { ProcessResponse } from '@/types';

/**
 * Download data as JSON file
 */
export const downloadJSON = (data: any, filename: string) => {
  const jsonString = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonString], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Download all results as a comprehensive markdown file with embedded data
 */
export const downloadAllResults = (results: ProcessResponse, documentId: string) => {
  const timestamp = new Date().toISOString().split('T')[0];

  // Create comprehensive markdown
  let markdown = resultsToMarkdown(results);

  // Add note about images
  markdown += `\n\n---\n\n## Additional Notes\n\n`;
  markdown += `This document was generated by Sage AI on ${new Date().toLocaleString()}.\n\n`;

  if (results.results?.slides && results.results.slides.some((s: any) => s.ai_image)) {
    markdown += `**Slides**: This presentation includes AI-generated images. Use the "Download Slides" button on the Slide Deck card to download them separately.\n\n`;
  }

  if (results.results?.visual && (results.results.visual as any).ai_infographic) {
    markdown += `**Visual Infographic**: An AI-generated infographic is available. Use the "Download High-Res" button on the Visual Infographic card to download it.\n\n`;
  }

  markdown += `\n---\n\nFor the complete data in JSON format, you can export it separately.\n`;

  const filename = `sage-complete-results-${documentId}-${timestamp}.md`;
  downloadMarkdown(markdown, filename);
};

/**
 * Download individual output as JSON
 */
export const downloadOutput = (
  outputData: any,
  outputType: string,
  documentId: string
) => {
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `sage-${outputType}-${documentId}-${timestamp}.json`;
  downloadJSON(outputData, filename);
};

/**
 * Download image (base64 data URL) as file
 */
export const downloadImage = (dataUrl: string, filename: string) => {
  const link = document.createElement('a');
  link.href = dataUrl;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

/**
 * Download slide image
 */
export const downloadSlideImage = (
  imageDataUrl: string,
  slideTitle: string,
  slideNumber: number,
  documentId: string
) => {
  const timestamp = new Date().toISOString().split('T')[0];
  const sanitizedTitle = slideTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  const filename = `sage-slide-${slideNumber}-${sanitizedTitle}-${timestamp}.png`;
  downloadImage(imageDataUrl, filename);
};

/**
 * Download comprehensive visual infographic
 */
export const downloadVisualInfographic = (
  imageDataUrl: string,
  documentId: string
) => {
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `sage-visual-infographic-${documentId}-${timestamp}.png`;
  downloadImage(imageDataUrl, filename);
};

/**
 * Download all slides as individual images
 */
export const downloadAllSlides = async (
  slides: any[],
  documentId: string
) => {
  for (let i = 0; i < slides.length; i++) {
    const slide = slides[i];
    if (slide.visual_url) {
      // Add delay between downloads to avoid browser blocking
      if (i > 0) {
        await new Promise(resolve => setTimeout(resolve, 200));
      }
      downloadSlideImage(slide.visual_url, slide.title, slide.id, documentId);
    }
  }
};

/**
 * Copy shareable link to clipboard
 */
export const copyShareLink = (documentId: string) => {
  const url = `${window.location.origin}/results?document_id=${documentId}`;
  navigator.clipboard.writeText(url).then(
    () => {
      // Success - you can add toast notification here
      return true;
    },
    () => {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = url;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      document.body.appendChild(textArea);
      textArea.select();
      try {
        document.execCommand('copy');
        return true;
      } catch (err) {
        return false;
      } finally {
        document.body.removeChild(textArea);
      }
    }
  );
};

/**
 * Download text content as markdown file
 */
export const downloadMarkdown = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Convert results to markdown format for export
 */
export const resultsToMarkdown = (results: ProcessResponse): string => {
  let markdown = `# Sage AI - Document Analysis Results\n\n`;
  markdown += `Generated: ${new Date().toLocaleString()}\n\n---\n\n`;

  // Summary
  if (results.results?.summary) {
    markdown += `## Summary\n\n${results.results.summary}\n\n---\n\n`;
  }

  // FAQs
  if (results.results?.faqs && results.results.faqs.length > 0) {
    markdown += `## Frequently Asked Questions\n\n`;
    results.results.faqs.forEach((faq: any, idx: number) => {
      markdown += `### ${idx + 1}. ${faq.question}\n\n${faq.answer}\n\n`;
    });
    markdown += `---\n\n`;
  }

  // Quiz
  if (results.results?.quiz && results.results.quiz.length > 0) {
    markdown += `## Quiz\n\n`;
    results.results.quiz.forEach((q: any, idx: number) => {
      markdown += `### Question ${idx + 1}: ${q.question}\n\n`;
      q.options.forEach((opt: string, optIdx: number) => {
        const letter = String.fromCharCode(65 + optIdx);
        markdown += `${letter}. ${opt}\n`;
      });
      markdown += `\n**Correct Answer:** ${q.correct_answer}\n`;
      markdown += `**Explanation:** ${q.explanation}\n\n`;
    });
    markdown += `---\n\n`;
  }

  // Debate
  if (results.results?.debate) {
    const debate = results.results.debate;
    markdown += `## Debate Topic: ${debate.topic}\n\n`;
    markdown += `### Side A: ${debate.side_a.position}\n\n`;
    debate.side_a.arguments.forEach((arg: string) => {
      markdown += `- ${arg}\n`;
    });
    markdown += `\n### Side B: ${debate.side_b.position}\n\n`;
    debate.side_b.arguments.forEach((arg: string) => {
      markdown += `- ${arg}\n`;
    });
    markdown += `\n---\n\n`;
  }

  // Slides
  if (results.results?.slides && results.results.slides.length > 0) {
    markdown += `## Presentation Slides\n\n`;
    results.results.slides.forEach((slide: any) => {
      if (slide.type === 'title') {
        markdown += `### ${slide.title}\n\n`;
      } else {
        markdown += `### Slide ${slide.id}: ${slide.title}\n\n`;
        if (slide.bullets && slide.bullets.length > 0) {
          slide.bullets.forEach((bullet: string) => {
            markdown += `- ${bullet}\n`;
          });
        }
        markdown += `\n`;
      }
    });
    markdown += `---\n\n`;
  }

  return markdown;
};

/**
 * Export results as markdown file
 */
export const exportAsMarkdown = (results: ProcessResponse, documentId: string) => {
  const markdown = resultsToMarkdown(results);
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `sage-results-${documentId}-${timestamp}.md`;
  downloadMarkdown(markdown, filename);
};
