/**
 * PDF Export utilities for Sage AI outputs
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import JSZip from 'jszip';
import html2canvas from 'html2canvas';
import { ProcessResponse } from '@/types';

const COLORS = {
  primary: [122, 155, 118], // sage
  secondary: [192, 120, 85], // terracotta
  text: [42, 40, 32],
  lightBg: [253, 251, 247],
};

/**
 * Add Sage AI header to PDF
 */
const addHeader = (doc: jsPDF, title: string) => {
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, 210, 25, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Sage AI', 10, 15);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 10, 21);
  doc.setTextColor(...COLORS.text);
};

/**
 * Add footer to PDF
 */
const addFooter = (doc: jsPDF, pageNumber: number) => {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by Sage AI • ${new Date().toLocaleDateString()} • Page ${pageNumber}`,
    105,
    pageHeight - 10,
    { align: 'center' }
  );
};

/**
 * Export Summary as PDF
 */
export const exportSummaryAsPDF = (summary: string, documentId: string) => {
  const doc = new jsPDF();
  addHeader(doc, 'Document Summary');

  doc.setFontSize(11);
  const lines = doc.splitTextToSize(summary, 180);
  let y = 35;

  lines.forEach((line: string) => {
    if (y > 270) {
      doc.addPage();
      addHeader(doc, 'Document Summary');
      y = 35;
    }
    doc.text(line, 15, y);
    y += 7;
  });

  addFooter(doc, 1);
  const timestamp = new Date().toISOString().split('T')[0];
  doc.save(`sage-summary-${documentId}-${timestamp}.pdf`);
};

/**
 * Export FAQs as PDF
 */
export const exportFAQsAsPDF = (faqs: any[], documentId: string) => {
  const doc = new jsPDF();
  addHeader(doc, 'Frequently Asked Questions');

  let y = 35;
  let pageNum = 1;

  faqs.forEach((faq, idx) => {
    if (y > 250) {
      addFooter(doc, pageNum);
      doc.addPage();
      addHeader(doc, 'Frequently Asked Questions');
      y = 35;
      pageNum++;
    }

    // Question
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.secondary);
    const qLines = doc.splitTextToSize(`Q${idx + 1}: ${faq.question}`, 180);
    qLines.forEach((line: string) => {
      doc.text(line, 15, y);
      y += 7;
    });

    y += 3;

    // Answer
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.text);
    const aLines = doc.splitTextToSize(faq.answer, 180);
    aLines.forEach((line: string) => {
      if (y > 270) {
        addFooter(doc, pageNum);
        doc.addPage();
        addHeader(doc, 'Frequently Asked Questions');
        y = 35;
        pageNum++;
      }
      doc.text(line, 15, y);
      y += 6;
    });

    y += 10;
  });

  addFooter(doc, pageNum);
  const timestamp = new Date().toISOString().split('T')[0];
  doc.save(`sage-faqs-${documentId}-${timestamp}.pdf`);
};

/**
 * Export Quiz as PDF
 */
export const exportQuizAsPDF = (quiz: any[], documentId: string) => {
  const doc = new jsPDF();
  addHeader(doc, 'Knowledge Quiz');

  let y = 35;
  let pageNum = 1;

  quiz.forEach((q, idx) => {
    if (y > 240) {
      addFooter(doc, pageNum);
      doc.addPage();
      addHeader(doc, 'Knowledge Quiz');
      y = 35;
      pageNum++;
    }

    // Question
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.secondary);
    const qLines = doc.splitTextToSize(`${idx + 1}. ${q.question}`, 180);
    qLines.forEach((line: string) => {
      doc.text(line, 15, y);
      y += 7;
    });

    y += 5;

    // Options
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.text);
    q.options.forEach((opt: string, optIdx: number) => {
      const letter = String.fromCharCode(65 + optIdx);
      doc.text(`${letter}. ${opt}`, 20, y);
      y += 6;
    });

    y += 3;

    // Answer
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.primary);
    doc.text(`Correct Answer: ${q.correct_answer}`, 15, y);
    y += 7;

    // Explanation
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    const expLines = doc.splitTextToSize(`Explanation: ${q.explanation}`, 180);
    expLines.forEach((line: string) => {
      if (y > 270) {
        addFooter(doc, pageNum);
        doc.addPage();
        addHeader(doc, 'Knowledge Quiz');
        y = 35;
        pageNum++;
      }
      doc.text(line, 15, y);
      y += 5;
    });

    y += 12;
  });

  addFooter(doc, pageNum);
  const timestamp = new Date().toISOString().split('T')[0];
  doc.save(`sage-quiz-${documentId}-${timestamp}.pdf`);
};

/**
 * Export Debate as PDF
 */
export const exportDebateAsPDF = (debate: any, documentId: string) => {
  const doc = new jsPDF();
  addHeader(doc, 'Multi-Perspective Analysis');

  let y = 35;
  let pageNum = 1;

  // Topic
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.secondary);
  const topicLines = doc.splitTextToSize(debate.topic, 180);
  topicLines.forEach((line: string) => {
    doc.text(line, 15, y);
    y += 8;
  });

  y += 10;

  // Supporting Arguments (Pros)
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.primary);
  doc.text('Supporting Arguments', 15, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.text);
  debate.pros.forEach((pro: any) => {
    if (y > 250) {
      addFooter(doc, pageNum);
      doc.addPage();
      addHeader(doc, 'Multi-Perspective Analysis');
      y = 35;
      pageNum++;
    }

    // Point
    doc.setFont('helvetica', 'bold');
    const pointLines = doc.splitTextToSize(`• ${pro.point}`, 175);
    pointLines.forEach((line: string) => {
      doc.text(line, 20, y);
      y += 6;
    });
    y += 2;

    // Explanation
    doc.setFont('helvetica', 'normal');
    const expLines = doc.splitTextToSize(pro.explanation, 175);
    expLines.forEach((line: string) => {
      if (y > 270) {
        addFooter(doc, pageNum);
        doc.addPage();
        addHeader(doc, 'Multi-Perspective Analysis');
        y = 35;
        pageNum++;
      }
      doc.text(line, 25, y);
      y += 5;
    });
    y += 8;
  });

  y += 5;

  // Challenging Arguments (Cons)
  if (y > 240) {
    addFooter(doc, pageNum);
    doc.addPage();
    addHeader(doc, 'Multi-Perspective Analysis');
    y = 35;
    pageNum++;
  }

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.primary);
  doc.text('Challenging Arguments', 15, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.text);
  debate.cons.forEach((con: any) => {
    if (y > 250) {
      addFooter(doc, pageNum);
      doc.addPage();
      addHeader(doc, 'Multi-Perspective Analysis');
      y = 35;
      pageNum++;
    }

    // Point
    doc.setFont('helvetica', 'bold');
    const pointLines = doc.splitTextToSize(`• ${con.point}`, 175);
    pointLines.forEach((line: string) => {
      doc.text(line, 20, y);
      y += 6;
    });
    y += 2;

    // Explanation
    doc.setFont('helvetica', 'normal');
    const expLines = doc.splitTextToSize(con.explanation, 175);
    expLines.forEach((line: string) => {
      if (y > 270) {
        addFooter(doc, pageNum);
        doc.addPage();
        addHeader(doc, 'Multi-Perspective Analysis');
        y = 35;
        pageNum++;
      }
      doc.text(line, 25, y);
      y += 5;
    });
    y += 8;
  });

  // Balanced Perspective
  if (debate.balanced_perspective) {
    if (y > 220) {
      addFooter(doc, pageNum);
      doc.addPage();
      addHeader(doc, 'Multi-Perspective Analysis');
      y = 35;
      pageNum++;
    }

    y += 5;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.primary);
    doc.text('Balanced Perspective', 15, y);
    y += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.text);
    const balancedLines = doc.splitTextToSize(debate.balanced_perspective, 180);
    balancedLines.forEach((line: string) => {
      if (y > 270) {
        addFooter(doc, pageNum);
        doc.addPage();
        addHeader(doc, 'Multi-Perspective Analysis');
        y = 35;
        pageNum++;
      }
      doc.text(line, 15, y);
      y += 6;
    });
  }

  addFooter(doc, pageNum);
  const timestamp = new Date().toISOString().split('T')[0];
  doc.save(`sage-debate-${documentId}-${timestamp}.pdf`);
};

/**
 * Export Slides as PDF with images
 */
export const exportSlidesAsPDF = async (slides: any[], documentId: string) => {
  const doc = new jsPDF('landscape');

  for (let i = 0; i < slides.length; i++) {
    const slide = slides[i];

    if (i > 0) {
      doc.addPage('landscape');
    }

    // Add slide number
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Slide ${i + 1} / ${slides.length}`, 270, 10, { align: 'right' });

    if (slide.ai_image) {
      // If slide has AI image, add it
      try {
        doc.addImage(slide.ai_image, 'PNG', 10, 15, 277, 170);
      } catch (error) {
        console.error('Failed to add image to PDF:', error);
        // Fallback to text
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...COLORS.primary);
        doc.text(slide.title, 148.5, 100, { align: 'center' });
      }
    } else if (slide.type === 'title') {
      // Title slide - special prominent styling
      // Add colored background
      doc.setFillColor(...COLORS.primary);
      doc.rect(0, 0, 297, 210, 'F');

      // Add title in white, centered
      doc.setFontSize(32);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      const titleLines = doc.splitTextToSize(slide.title, 260);
      let y = 105 - (titleLines.length * 6); // Center vertically
      titleLines.forEach((line: string) => {
        doc.text(line, 148.5, y, { align: 'center' });
        y += 14;
      });

      // Add subtitle if present
      if (slide.bullets && slide.bullets.length > 0 && slide.bullets[0]) {
        y += 10;
        doc.setFontSize(16);
        doc.setFont('helvetica', 'normal');
        doc.text(slide.bullets[0], 148.5, y, { align: 'center' });
      }
    } else {
      // Regular text-only slide
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.primary);
      const titleLines = doc.splitTextToSize(slide.title, 250);
      let y = 50;
      titleLines.forEach((line: string) => {
        doc.text(line, 148.5, y, { align: 'center' });
        y += 12;
      });

      if (slide.bullets && slide.bullets.length > 0) {
        y += 20;
        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...COLORS.text);

        slide.bullets.forEach((bullet: string) => {
          const bulletLines = doc.splitTextToSize(`• ${bullet}`, 240);
          bulletLines.forEach((line: string) => {
            doc.text(line, 30, y);
            y += 8;
          });
          y += 4;
        });
      }
    }
  }

  const timestamp = new Date().toISOString().split('T')[0];
  doc.save(`sage-slides-${documentId}-${timestamp}.pdf`);
};

/**
 * Export Mind Map as PNG (capture the DOM element)
 */
export const exportMindMapAsPNG = async (elementId: string, documentId: string): Promise<Blob> => {
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error('Mind map element not found');
  }

  const canvas = await html2canvas(element, {
    backgroundColor: '#FDFBF7',
    scale: 2,
  });

  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      if (blob) {
        resolve(blob);
      }
    }, 'image/png');
  });
};

/**
 * Download all outputs as ZIP
 */
export const downloadAllAsZip = async (results: ProcessResponse, documentId: string) => {
  const zip = new JSZip();
  const timestamp = new Date().toISOString().split('T')[0];

  try {
    // Add Summary PDF
    if (results.results?.summary) {
      const doc = new jsPDF();
      addHeader(doc, 'Document Summary');
      doc.setFontSize(11);
      const lines = doc.splitTextToSize(results.results.summary, 180);
      let y = 35;
      lines.forEach((line: string) => {
        if (y > 270) {
          doc.addPage();
          addHeader(doc, 'Document Summary');
          y = 35;
        }
        doc.text(line, 15, y);
        y += 7;
      });
      addFooter(doc, 1);
      zip.file(`1-summary.pdf`, doc.output('blob'));
    }

    // Add FAQs PDF
    if (results.results?.faqs && results.results.faqs.length > 0) {
      const doc = new jsPDF();
      addHeader(doc, 'FAQs');
      let y = 35;
      results.results.faqs.forEach((faq: any, idx: number) => {
        if (y > 250) {
          doc.addPage();
          addHeader(doc, 'FAQs');
          y = 35;
        }
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(`Q${idx + 1}: ${faq.question}`, 15, y);
        y += 10;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        const aLines = doc.splitTextToSize(faq.answer, 180);
        aLines.forEach((line: string) => {
          doc.text(line, 15, y);
          y += 6;
        });
        y += 10;
      });
      addFooter(doc, 1);
      zip.file(`2-faqs.pdf`, doc.output('blob'));
    }

    // Add Quiz PDF
    if (results.results?.quiz && results.results.quiz.length > 0) {
      const doc = new jsPDF();
      addHeader(doc, 'Quiz');
      let y = 35;
      results.results.quiz.forEach((q: any, idx: number) => {
        if (y > 240) {
          doc.addPage();
          addHeader(doc, 'Quiz');
          y = 35;
        }
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(`${idx + 1}. ${q.question}`, 15, y);
        y += 10;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        q.options.forEach((opt: string, optIdx: number) => {
          doc.text(`${String.fromCharCode(65 + optIdx)}. ${opt}`, 20, y);
          y += 6;
        });
        y += 5;
        doc.setFont('helvetica', 'bold');
        doc.text(`Answer: ${q.correct_answer}`, 15, y);
        y += 12;
      });
      addFooter(doc, 1);
      zip.file(`3-quiz.pdf`, doc.output('blob'));
    }

    // Add Debate PDF
    if (results.results?.debate) {
      const doc = new jsPDF();
      addHeader(doc, 'Multi-Perspective Analysis');
      let y = 35;
      let pageNum = 1;

      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.secondary);
      const topicLines = doc.splitTextToSize(results.results.debate.topic, 180);
      topicLines.forEach((line: string) => {
        doc.text(line, 15, y);
        y += 8;
      });
      y += 10;

      // Supporting Arguments
      doc.setFontSize(12);
      doc.setTextColor(...COLORS.primary);
      doc.text('Supporting Arguments', 15, y);
      y += 10;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.text);

      results.results.debate.pros.forEach((pro: any) => {
        if (y > 250) {
          addFooter(doc, pageNum);
          doc.addPage();
          addHeader(doc, 'Multi-Perspective Analysis');
          y = 35;
          pageNum++;
        }
        const lines = doc.splitTextToSize(`• ${pro.point}`, 175);
        lines.forEach((line: string) => {
          doc.text(line, 20, y);
          y += 6;
        });
        y += 8;
      });

      y += 10;
      if (y > 240) {
        addFooter(doc, pageNum);
        doc.addPage();
        addHeader(doc, 'Multi-Perspective Analysis');
        y = 35;
        pageNum++;
      }

      // Challenging Arguments
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.primary);
      doc.text('Challenging Arguments', 15, y);
      y += 10;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.text);

      results.results.debate.cons.forEach((con: any) => {
        if (y > 250) {
          addFooter(doc, pageNum);
          doc.addPage();
          addHeader(doc, 'Multi-Perspective Analysis');
          y = 35;
          pageNum++;
        }
        const lines = doc.splitTextToSize(`• ${con.point}`, 175);
        lines.forEach((line: string) => {
          doc.text(line, 20, y);
          y += 6;
        });
        y += 8;
      });

      addFooter(doc, pageNum);
      zip.file(`4-debate.pdf`, doc.output('blob'));
    }

    // Add Slides PDF
    if (results.results?.slides && results.results.slides.length > 0) {
      const doc = new jsPDF('landscape');
      for (let i = 0; i < results.results.slides.length; i++) {
        const slide = results.results.slides[i];
        if (i > 0) doc.addPage('landscape');

        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text(`Slide ${i + 1}`, 270, 10, { align: 'right' });

        if (slide.ai_image) {
          try {
            doc.addImage(slide.ai_image, 'PNG', 10, 15, 277, 170);
          } catch (error) {
            doc.setFontSize(16);
            doc.text(slide.title, 148.5, 100, { align: 'center' });
          }
        } else if (slide.type === 'title') {
          // Title slide - special prominent styling
          doc.setFillColor(...COLORS.primary);
          doc.rect(0, 0, 297, 210, 'F');
          doc.setFontSize(32);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(255, 255, 255);
          const titleLines = doc.splitTextToSize(slide.title, 260);
          let y = 105 - (titleLines.length * 6);
          titleLines.forEach((line: string) => {
            doc.text(line, 148.5, y, { align: 'center' });
            y += 14;
          });
          if (slide.bullets && slide.bullets.length > 0 && slide.bullets[0]) {
            y += 10;
            doc.setFontSize(16);
            doc.setFont('helvetica', 'normal');
            doc.text(slide.bullets[0], 148.5, y, { align: 'center' });
          }
        } else {
          // Regular text-only slide
          doc.setFontSize(24);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(...COLORS.primary);
          const titleLines = doc.splitTextToSize(slide.title, 250);
          let y = 50;
          titleLines.forEach((line: string) => {
            doc.text(line, 148.5, y, { align: 'center' });
            y += 12;
          });
          if (slide.bullets && slide.bullets.length > 0) {
            y += 20;
            doc.setFontSize(12);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...COLORS.text);
            slide.bullets.forEach((bullet: string) => {
              const bulletLines = doc.splitTextToSize(`• ${bullet}`, 240);
              bulletLines.forEach((line: string) => {
                doc.text(line, 30, y);
                y += 8;
              });
              y += 4;
            });
          }
        }
      }
      zip.file(`5-slides.pdf`, doc.output('blob'));
    }

    // Add Visual Infographic PNG
    if (results.results?.visual && (results.results.visual as any).ai_infographic) {
      const imageData = (results.results.visual as any).ai_infographic;
      const base64Data = imageData.split(',')[1];
      zip.file(`6-visual-infographic.png`, base64Data, { base64: true });
    }

    // Add Mind Map PNG (if available)
    try {
      const mindMapBlob = await exportMindMapAsPNG('mindmap-container', documentId);
      zip.file(`7-mindmap.png`, mindMapBlob);
    } catch (error) {
      console.log('Mind map export skipped:', error);
    }

    // Generate ZIP
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `sage-complete-results-${documentId}-${timestamp}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

  } catch (error) {
    console.error('Error creating ZIP:', error);
    throw error;
  }
};
